import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='felx felx-row justify-between p-4'>
          <div>
            Company Name
          </div>
          <nav>
            <ul className='grid grid-cols-4 gap-2'>
              <li><Link href='/'></Link></li>
              <li><Link href='/products'>Products</Link></li>
              <li><Link href='/blog'>Blog</Link></li>
              <li><Link href='/contact'>Contact</Link></li>
            </ul>
          </nav>
        </header>
        <div className='content'>{children}</div>
      </body>
    </html>
  )
}
